### ISSUE TITLE
HTTP access control

### ISSUE THREAD

**Issue by Bvkb** [tomcx/tame4#7]
Hi,

I'm testing TAME4 on different hardware/possibilities.

Connecting remotely to
CX5130 / CX9020

Connecting TAME4 to ADS on CX9020 I run into the HTTP access control and pre-flight errors.
On a CX5130 with windows embedded standard 7 you can add the needed headers into IIS and everything is running fine.

The CX9020 running windows embedded compact I see no possibility to add the needed headers somewhere.
As I am not a javascript expert I had no luck trying xdomain or any proxy possibility to bypass this issue.

Do you see any resolution to this?

Great work!

Bryan

**Comment by tomcx** [comment]
Sorry, I have no idea how to solve this. You could deactivate it in the browser.

**Comment by vancassa** [comment]
I'm connecting to ADS on CX9020 with TAME4 and run into the message
"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

What I did to resolve it is to change the content of the webservice.js, for the "serviceUrl", use the IP address of the CX9020 instead of "localhost". 

For example, mine is "http://192.168.1.25/TcAdsWebservice/TcAdsWebService.dll"
