### ISSUE TITLE
TPY, example

### ISSUE THREAD

**Issue by nelinnemann** [tomcx/tame4#8]
Hi, first off really awesome library you have put together here.
Much easier to work with than the stuff Beckhoff put together.

One request.
Is it possible to make a small example to demonstrate the advantages of using the tpy file as described in the readme?
Digging in the source did not give me much.

Best regards

**Comment by tomcx** [comment]
Hi, I think it's difficult to explain with an example cause there is no difference except the few lines in the client definition. Another problem is that my TPY not necessarily works on other systems. That's why I didn't add an example for this.

In the docs at page 63 you'll find a short explanation of the different methods and 2 tables. They show what kind of variables you can access with each approach. So if you don't want to read/write local variables and parameters of FB instances or single elements of structures /arrays you don't need the TPY. It just depends on what kind of PLC variables you want to read or write.

**Comment by nelinnemann** [comment]
Ok, just seemed like there were some benefits of using the TPY.

Thx for the great work.
